[SoC] Go-wechaty Github Actions Optimization
wechaty/go-wechaty pull request #68
Opened 2020-09-09 01:35 UTC by Nebell

2020-09-10 00:42 UTC, dingdayu commented
请在 https://github.com/wechaty/go-wechaty-getting-started/pull/8 合并后合入。

2020-09-10 00:45 UTC, dingdayu commented
@Nebell 看下这里 `REPO_ACCESS_TOKEN` 是否可以使用 `GH_TOKEN`，如果不可以，还需要 @huan 提供支持。

2020-09-10 02:31 UTC, Nebell commented
> @Nebell 看下这里 `REPO_ACCESS_TOKEN` 是否可以使用 `GH_TOKEN`，如果不可以，还需要 @huan 提供支持。

应该不能使用 `GH_TOKEN` 替代，详见 [actions/repository-dispatch](https://github.com/marketplace/actions/repository-dispatch#token)。

2020-09-15 10:35 UTC, dingdayu commented
@huan 
Hi,卓桓 这个 PR 需要一个具有  `` 项目  `write` 权限的 token， @Nebell 有在上面提到原因和链接。

2020-09-15 10:40 UTC, dingdayu approved these changes
LGTM

2020-09-15 10:43 UTC, dingdayu requested changes
请把 `Repository Dispatch` 转移到 `Tags` 事件里，如果尚未设置这个事件，请新增一个，不能直接放在 `push` 或 `pr` 里。

2020-09-15 12:53 UTC, Nebell commented
> 
> 
> 请把 `Repository Dispatch` 转移到 `Tags` 事件里，如果尚未设置这个事件，请新增一个，不能直接放在 `push` 或 `pr` 里。

已经另外新建一个文件

2020-09-16 04:20 UTC, dingdayu approved these changes
LGTM

2020-09-18 01:50 UTC, dchaofei approved these changes

2020-09-18 01:51 UTC, merged